const Data = [
  // Wedding Collection
  { id: 1, name: "Bridal Set", description: "Elegant bridal set with diamond accents.", price: 20000, image: "/images/wedding/1.jpg", category: "Wedding Collection", subimages: ["/images/wedding/1.1.jpg", "/images/wedding/1.2.jpg","/images/wedding/1.3.jpg"] },
  { id: 2, name: "Wedding Necklace", description: "Stunning pure Gold necklace for weddings.", price: 15000, image: "/images/wedding/2.jpg", category: "Wedding Collection", subimages: ["/images/wedding/2.1.jpg", "/images/wedding/2.2.jpg","/images/wedding/2.3.jpg"] },
  { id: 3, name: "Bridal Earrings", description: "Beautiful pearl & diamond earrings for brides.", price: 8000, image: "/images/wedding/3.jpg", category: "Wedding Collection", subimages: ["/images/wedding/3.1.jpg.jpg", "/images/wedding/3.2.jpg","/images/wedding/3.3.jpg"] },
  { id: 4, name: "Gold Bangles", description: "Heavy Gold bangles for wedding sets.", price: 12000, image: "/images/wedding/4.jpg", category: "Wedding Collection", subimages: ["/images/wedding/4.1.jpg", "/images/wedding/4.2.jpg"," /images/wedding/4.3.jpg"] },
  { id: 5, name: "Diamond-pearl Wedding Set", description: "Diamond-studded wedding set for a timeless look.", price: 25000, image: "/images/wedding/5.jpg", category: "Wedding Collection", subimages: ["/images/wedding/5.1.jpg", "/images/wedding/5.2.jpg","/images/wedding/5.3.jpg"] },
  { id: 6, name: "Bridal Gold Wedding Necklace", description: "Elegant gold wedding set with intricate designs.", price: 18000, image: "/images/wedding/6.jpg", category: "Wedding Collection", subimages: ["/images/wedding/6.1.jpg", "/images/wedding/6.2.jpg","/images/wedding/6.3.jpg"] },
  { id: 7, name: "Traditional Bridal Necklace", description: "Traditional bridal necklace with gold and red stones.", price: 22000, image: "/images/wedding/7.jpg", category: "Wedding Collection", subimages: ["/images/wedding/7.1.jpg", "/images/wedding/7.2.jpg","/images/wedding/7.3.jpg"] },
  { id: 8, name: "Beautiful  Pearl Wedding Set", description: "Elegant pearl wedding set with touch of Gold.", price: 15000, image: "/images/wedding/8.jpg", category: "Wedding Collection", subimages: ["/images/wedding/8.1.jpg", "/images/wedding/8.2.jpg","/images/wedding/8.3.jpg"] },
  { id: 9, name: "Diamond Pendant Wedding Set", description: "Diamond pendant with matching earrings.", price: 23000, image: "/images/wedding/9.jpg", category: "Wedding Collection", subimages: ["/images/wedding/9.1.jpg", "/images/wedding/9.2.jpg","/images/wedding/9.3.jpg"] },
  { id: 10, name: "Classic Gold Wedding Ring", description: "Classic gold wedding ring with a touch of green.", price: 5000, image: "/images/wedding/10.jpg", category: "Wedding Collection", subimages: ["/images/wedding/10.1.jpg", "/images/wedding/10.2.jpg","/images/wedding/10.3.jpg"]},
  // Rings
  { id: 11, name: "Gold Ring", description: "Simple and elegant gold ring.", price: 2500, image: "/images/rings/11.webp", category: "Rings", subimages: ["/images/rings/11.jpg", "/images/rings/11.2.webp","/images/rings/11.3.webp"] },
  { id: 12, name: "Silver Ring", description: "Stylish silver ring.", price: 1500, image: "/images/rings/12.webp", category: "Rings", subimages: ["/images/rings/12.1.jpg", "/images/rings/12.2.jpg","/images/rings/12.3.jpg"] },
  { id: 13, name: "Platinum Ring", description: "Elegant platinum ring with subtle design.", price: 4000, image: "/images/rings/13.jpg", category: "Rings", subimages: ["/images/rings/13.1.jpg", "/images/rings/13.2.jpg","/images/rings/13.3.jpg"] },
  { id: 14, name: "Diamond Ring", description: "Stunning diamond ring.", price: 15000, image: "/images/rings/14.webp", category: "Rings", subimages: ["/images/rings/14.1.webp", "/images/rings/14.2.webp","/images/rings/14.3.jpg"] },
  { id: 15, name: "Gold Wedding Ring", description: "Simple gold wedding ring.", price: 5000, image: "/images/rings/15.webp", category: "Rings", subimages: ["/images/rings/15.1.webp", "/images/rings/15.2.webp","/images/rings/15.3.webp"]},
  { id: 16, name: "Solitaire  Ring", description: "Elegant solitaire engagement ring.", price: 10000, image: "/images/rings/16.webp", category: "Rings", subimages: ["/images/rings/16.webp", "/images/rings/16.1.webp","/images/rings/16.2.webp"]},
  { id: 17, name: "Signet Ring", description: "Stylish gold signet ring.", price: 3000, image: "/images/rings/17.webp", category: "Rings", subimages: ["/images/rings/17.1.webp", "/images/rings/17.2webp","/images/rings/17.3.webp"] },
  { id: 18, name: "Diamond Solitaire Ring", description: "Exquisite diamond solitaire ring.", price: 20000, image: "/images/rings/18.jpg", category: "Rings", subimages: ["/images/rings/18.1.webp", "/images/rings/18.2.webp","/images/rings/18.3.webp"] },
  { id: 19, name: "Gold Signet Ring", description: "Stylish gold signet ring.", price: 2500, image: "/images/rings/19.webp", category: "Rings", subimages: ["/images/rings/19.webp", "/images/rings/19.1.webp","/images/rings/19.2.webp"]},
  { id: 20, name: "Engagement Ring", description: "Stunning engagement ring with diamond.", price: 8000, image: "/images/rings/20.webp", category: "Rings", subimages: ["/images/rings/20.webp", "/images/rings/20.1.webp","/images/rings/20.2.webp"] },

  // Bracelet
  { id: 21, name: "Gold Bracelet", description: "Elegant gold bracelet.", price: 7000, image: "/images/bracelet/21.webp", category: "Bracelet", subimages: ["/images/bracelet/21.1.webp", "/images/bracelet/21.2.webp.jpg"] },
  { id: 22, name: "Silver Bracelet", description: "Sleek silver bracelet.", price: 4000, image: "/images/bracelet/22.webp", category: "Bracelet", subimages: ["/images/bracelet/22.webp", "/images/bracelet/22.webp", "/images/bracelet/22.2.jpg"]},
  { id: 23, name: "Diamond Bracelet", description: "Diamond-studded bracelet.", price: 12000, image: "/images/bracelet/23.jpg", category: "Bracelet", subimages: ["/images/bracelet/23.jpg", "/images/bracelet/23.1.webp","/images/bracelet/23.2.webp"] },
  { id: 24, name: "Pearl Bracelet", description: "Stylish pearl bracelet.", price: 2000, image: "/images/bracelet/24.jpg", category: "Bracelet", subimages: ["/images/bracelet/24.1.webp", "/images/bracelet/24.2.jpg","/images/bracelet/24.3.jpg"] },
  { id: 25, name: "Gold Chain Bracelet", description: "Gold chain bracelet.", price: 6000, image: "/images/bracelet/25.jpg", category: "Bracelet", subimages: ["/images/bracelet/25.jpg", "/images/bracelet/25.1.jpg","/images/bracelet/25.2.jpg"]},
  { id: 26, name: "Silver Cuff Bracelet", description: "Stylish silver cuff bracelet.", price: 3500, image: "/images/bracelet/26.webp", category: "Bracelet", subimages:  ["/images/bracelet/26.webp", "/images/bracelet/26.1.webp","/images/bracelet/26.2.jpg"] },
  { id: 27, name: " Linked Bracelet", description: "Elegant gold Linked bracelet.", price: 9000, image: "/images/bracelet/27.webp", category: "Bracelet", subimages: ["/images/bracelet/27.1.jpg", "/images/bracelet/27.2.jpg","/images/bracelet/27.3.jpg"] },
  { id: 28, name: "Charm Bracelet", description: "Charming bracelet with various pendants.", price: 4000, image: "/images/bracelet/28.webp", category: "Bracelet", subimages: ["/images/bracelet/278.webp", "/images/bracelet/28.1.webp","/images/bracelet/28.2.webp"] },
  { id: 29, name: "Tennis Bracelet", description: "Diamond tennis bracelet.", price: 18000, image: "/images/bracelet/29.webp", category: "Bracelet", subimages: ["/images/bracelet/29.1.webp", "/images/bracelet/29.2.webp" , "/images/bracelet/29.3.jpg"]},
  { id: 30, name: "Bangle Bracelet", description: "Simple gold bangle bracelet.", price: 5000, image: "/images/bracelet/30.webp", category: "Bracelet", subimages: ["/images/bracelet/30.webp", "/images/bracelet/30.1.webp","/images/bracelet/30.webp"] },

  //bangles
{ id: 31, name: "Gold Bangles", description: "Traditional gold bangles.", price: 12000, image: "/images/bangles/30.jpg", category: "Bangles", subimages: ["/images/bangles/31.jpg", "/images/bangles/31.1.webp","/images/bangles/31.2.jpg"] },
{ id: 32, name: "Diamond Bangles", description: "Exquisite diamond bangles.", price: 25000, image: "/images/bangles/32.jpg", category: "Bangles", subimages: ["/images/bangles/32.jpg", "/images/bangles/32.1.jpg","/images/bangles/32.2.jpg"] },
{ id: 33, name: " Ruby & Diamond Bangles", description: "Elegant ruby & diamond bangles.", price: 15000, image: "/images/bangles/33.jpg", category: "Bangles", subimages: ["/images/bangles/33.jpg","/images/bangles/33.1.jpg", "/images/bangles/33.jpg"] },
{ id: 34, name: "Silver-Gold Bangles", description: "Stylish silver-Gold bangles.", price: 7000, image: "/images/bangles/34.webp", category: "Bangles", subimages: ["/images/bangles/34.webp", "/images/bangles/34.1.jpg","/images/bangles/34.webp"] },
{ id: 35, name: "Gold Bridal Bangles", description: "Gold bridal bangles with intricate design.", price: 18000, image: "/images/bangles/35.webp", category: "Bangles", subimages: ["/images/bangles/35.webp", "/images/bangles/35.1.webp","/images/bangles/35.webp"] },
{ id: 36, name: "Pearl Bangles", description: "Elegant pearl-studded bangles.", price: 13000, image: "/images/bangles/36.webp", category: "Bangles", subimages: ["/images/bangles/36.1.webp", "/images/bangles/36.2.webp","/images/bangles/36.3.webp"] },
{ id: 37, name: "Ruby Bangles", description: "Ruby-studded gold bangles.", price: 22000, image: "/images/bangles/37.webp", category: "Bangles", subimages: ["/images/bangles/37.webp", "/images/bangles/37.1.jpg","/images/bangles/37.2.jpg"] },
{ id: 38, name: "Kundan Bangles", description: "Traditional Kundan bangles.", price: 16000, image: "/images/bangles/38.webp", category: "Bangles", subimages: ["/images/bangles/38.webp", "/images/bangles/38.1.jpg","/images/bangles/38.2.jpg"] },
{ id: 39, name: "Thin Diamond Bangles", description: "Delicate lightweight diamond bangle.", price: 14000, image: "/images/bangles/39.webp", category: "Bangles", subimages: ["/images/bangles/39.webp", "/images/bangles/39.1.webp","/images/bangles/39.2.webp"] },
{ id: 40, name: "Heavy Wedding Bangles", description: "Elegant heavy wedding bangles.", price: 20000, image: "/images/bangles/40.webp", category: "Bangles", subimages: ["/images/bangles/40.webp", "/images/bangles/40.1.webp","/images/bangles/40.1.webp"] },

//necklace
{ id: 41, name: "Gold Necklace", description: "Simple gold necklace.", price: 10000, image: "/images/necklace/41.jpg", category: "Necklaces", subimages: ["/images/bangles/41.webp", "/images/bangles/41.1.jpg","/images/bangles/41.2.jpg"] },
{ id: 42, name: "Diamond Necklace", description: "Exquisite diamond necklace.", price: 25000, image: "/images/necklace/42.webp", category: "Necklaces", subimages: ["/images/necklace/42.webp", "/images/necklace/42.1.webp","/images/necklace/42.2.webp"] },
{ id: 43, name: "Gold Pendant Necklace", description: "Gold necklace with a pendant.", price: 15000, image: "/images/necklace/43.webp", category: "Necklaces", subimages: ["/images/necklace/43.1.jpg", "/images/necklace/43.2./jpg","/images/necklace/43.3.jpg"] },
{ id: 44, name: "Pearl Necklace", description: "Elegant pearl necklace.", price: 12000, image: "/images/necklace/44.webp", category: "Necklaces", subimages: ["/images/necklace/44.webp", "/images/necklace/44.1.webp","/images/necklace/44.2.webp"] },
{ id: 45, name: "Rose Gold Necklace", description: "Stunning platinum necklace.", price: 18000, image: "/images/necklace/45.jpg", category: "Necklaces", subimages: ["/images/necklace/45.1.webp", "/images/necklace/45.2.jpg","/images/necklace/45.jpg"] },
{ id: 46, name: "Silver Necklace", description: "Simple silver necklace.", price: 5000, image: "/images/necklace/46.webp", category: "Necklaces", subimages: ["/images/necklace/46.webp", "/images/necklace/46.1.webp","/images/necklace/46.webp"] },
{ id: 47, name: "Diamond Necklace", description: "Simple diamond pendant.", price: 8000, image: "/images/necklace/47.webp", category: "Necklaces", subimages: ["/images/necklace/47.1.jpg", "/images/necklace/47.2.webp","/images/necklace/47.3.jpg"] },
{ id: 48, name: "Ruby Necklace", description: "Elegant ruby necklace.", price: 22000, image: "/images/necklace/48.jpg", category: "Necklaces", subimages: ["/images/necklace/48.1.webp", "/images/necklace/48.2.jpg","/images/necklace/48.3.jpg"] },
{ id: 49, name: "Gold Necklace with Pendant", description: "Gold necklace with attached pendant.", price: 11000, image: "/images/necklace/49.jpg", category: "Necklaces", subimages: ["/images/necklace/49.1.webp", "/images/necklace/49.2.webp"] },
{ id: 50, name: "Kundan Necklace", description: "Traditional Kundan necklace.", price: 15000, image: "/images/necklace/50.jpg", category: "Necklaces", subimages: ["/images/necklace/50.1.jpg", "/images/necklace/50.2.webp","/images/necklace/50.3.jpg"] },
 
//chain and pendants
{ id: 51, name: "Gold Chain", description: "Classic gold chain.", price: 5000, image: "/images/chain and pendants/51.jpg", category: "Chain & Pendants", subimages: ["/images/chain and pendants/51.jpg", "/images/chain and pendants/51.1.jpg","/images/chain and pendants/51.2.webp"] },
{ id: 52, name: "Diamond Pendant", description: "Stunning diamond pendant.", price: 12000, image: "/images/chain and pendants/52.webp", category: "Chain & Pendants", subimages: ["/images/chain and pendants/52.webp", "/images/chain and pendants/51.1.webp","/images/chain and pendants/51.webp"] },
{ id: 53, name: "Silver Chain", description: "Stylish silver chain.", price: 3000, image: "/images/chain and pendants/53.webp", category: "Chain & Pendants", subimages: ["/images/chain and pendants/53.webp", "/images/chain and pendants/53.1.jpg","/images/chain and pendants/53.3.jpg"] },
{ id: 54, name: "Gold Pendant", description: "Elegant gold pendant.", price: 7000, image: "/images/chain and pendants/54.webp", category: "Chain & Pendants", subimages: ["/images/chain and pendants/54.webp", "/images/chain and pendants/54.1.webp","/images/chain and pendants/54.webp"] },
{ id: 55, name: "Platinum Chain", description: "Sleek platinum chain.", price: 10000, image: "/images/chain and pendants/55.webp", category: "Chain & Pendants", subimages: ["/images/chain and pendants/55.1.webp", "/images/chain and pendants/55.webp","/images/chain and pendants/55.1.webp"] },
{ id: 56, name: "Ruby Pendant", description: "Ruby-studded pendant.", price: 8000, image: "/images/chain and pendants/56.webp", category: "Chain & Pendants", subimages: ["/images/chain and pendants/56.webp", "/images/chain and pendants/56.1.webp","/images/chain and pendants/56.webp"] },
{ id: 57, name: "Solitaire Pendant", description: "Solitaire pendant in diamond.", price: 15000, image: "/images/chain and pendants/57.jpg", category: "Chain & Pendants", subimages: ["/images/chain and pendants/57.jpg", "/images/chain and pendants/57.1.jpg","/images/chain and pendants/57.jpg"] },
{ id: 58, name: "Emerald Pendant", description: "Emerald-studded pendant.", price: 12000, image: "/images/chain and pendants/58.webp", category: "Chain & Pendants", subimages: ["/images/chain and pendants/58.webp","/images/chain and pendants/58.1.jpg" , "/images/chain and pendants/58.webp"] },
{ id: 59, name: "Gold Chain & Pendant", description: "Gold chain with pendant.", price: 13000, image: "/images/chain and pendants/59.webp", category: "Chain & Pendants", subimages: ["/images/chain and pendants/59.jpg", "/images/chain and pendants/59.2.jpg","/images/chain and pendants/59.webp"] },
{ id: 60, name: "Diamond Chain", description: "Diamond-studded chain.", price: 20000, image: "/images/chain and pendants/60.webp", category: "Chain & Pendants", subimages: ["/images/chain and pendants/60.webp", "/images/chain and pendants/60.1.jpg","/images/chain and pendants/60.webp"] },

// Diamond Collection

  { id: 61, name: "Diamond Ring", description: "Brilliant diamond ring.", price: 25000, image: "/images/chain and pendants/61.jpg", category: "Diamond Collection", subimages: ["/images/chain and pendants/61.jpg", "/images/chain and pendants/61.1.jpg","/images/chain and pendants/61.2.jpg"] },
  { id: 62, name: "Diamond Earrings", description: "Sparkling diamond earrings.", price: 20000, image: "/images/chain and pendants/62.jpg", category: "Diamond Collection", subimages: ["/images/chain and pendants/62.jpg","/images/chain and pendants/62.1.webp" ,"/images/chain and pendants/62.jpg"] },
  { id: 63, name: "Diamond Pendant", description: "Elegant diamond pendant.", price: 15000, image: "/images/chain and pendants/63.webp", category: "Diamond Collection", subimages: ["/images/chain and pendants/63.webp", "/images/chain and pendants/63.1.webp","/images/chain and pendants/63.webp"] },
  { id: 64, name: "Diamond Necklace", description: "Exquisite diamond necklace.", price: 30000, image: "/images/chain and pendants/64.webp", category: "Diamond Collection", subimages: ["/images/chain and pendants/64.webp", "/images/chain and pendants/64.1.jpg","/images/chain and pendants/64.2.jpg"] },
  { id: 65, name: "Diamond Bracelet", description: "Diamond bracelet with intricate design.", price: 22000, image: "/images/chain and pendants/65.webp", category: "Diamond Collection", subimages: ["/images/chain and pendants/65.1.jpg","/images/chain and pendants/65.webp" ,"/images/chain and pendants/65.2.jpg"] },
  { id: 66, name: "Diamond Earrings & Necklace", description: "Elegant earrings and necklace set.", price: 40000, image: "/images/chain and pendants/66.webp", category: "Diamond Collection", subimages: ["/images/chain and pendants/66.1.webp", "/images/chain and pendants/66.2.webp","/images/chain and pendants/66.3.webp"] },
  { id: 67, name: "Diamond Solitaire Ring", description: "Classic diamond solitaire ring.", price: 35000, image: "/images/chain and pendants/67.webp", category: "Diamond Collection", subimages: ["/images/chain and pendants/67.webp","/images/chain and pendants/67.1.jpg" ,"/images/chain and pendants/67.2.jpg"] },
  { id: 68, name: "Diamond Wedding Bangle", description: "Elegant diamond wedding bangle.", price: 25000, image: "/images/chain and pendants/68.webp", category: "Diamond Collection", subimages: ["/images/chain and pendants/68.webp", "/images/chain and pendants/68.1.webp","/images/chain and pendants/68.2.webp"] },
  { id: 69, name: "Diamond Earrings", description: "Exquisite diamond Earrings.", price: 18000, image: "/images/chain and pendants/69.webp", category: "Diamond Collection", subimages: ["/images/chain and pendants/69.1.webp", "/images/chain and pendants/69.2.webp","/images/chain and pendants/69.3.webp"] },
  { id: 70, name: "Diamond Pendant Necklace", description: "Elegant diamond pendant necklace.", price: 20000, image: "/images/chain and pendants/70.webp", category: "Diamond Collection", subimages: ["/images/chain and pendants/70.1.webp", "/images/chain and pendants/70.2.webp","/images/chain and pendants/70.3.webp"] }

];
export default Data;